
version: '2'

services:
    reverseproxy:
        build: /home/favio/composeset2
        ports:
            - 8080:8080
            - 8081:8081
        restart: always

    nginx:
        build: /home/favio/composeset/nginxs
        depends_on:
            - reverseproxy
        volumes:
            - /home/favio/composeset/nginxs/web:/usr/share/nginx/html
        restart: always

    redis:
        image: redis
        restart: always

    flask:
        build: /home/favio/composeset/python
        depends_on:
            - reverseproxy
            - redis
        volumes:
        - /home/favio/composeset/python/flaskapp:/flaskapp        
        stdin_open: true
        tty: true
